export const allCompanies = [
  {
    id: "1",
    name: "Kahve Dünyası",
    description: "Türk kahvesi ve tatlı çeşitleri.",
    image: "https://picsum.photos/220/220",
    star: 4.6,
    distance: 3.5,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
  {
    id: "2",
    name: "McDonald's",
    description: "Hızlı ve lezzetli yemekler.",
    image: "https://picsum.photos/240/240",
    star: 4.1,
    distance: 2.0,
    category: ["Burger"],
    city: "Ankara",
  },
  {
    id: "3",
    name: "Domino's Pizza",
    description: "Hızlı teslimat ve taze malzemeler.",
    image: "https://picsum.photos/210/210",
    star: 4.2,
    distance: 3.0,
    category: ["Pizza"],
    city: "Sakarya",
  },
  {
    id: "4",
    name: "Starbucks",
    description: "Kahve ve tatlı keyfi.",
    image: "https://picsum.photos/230/230",
    star: 4.8,
    distance: 0.5,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
  {
    id: "5",
    name: "Burger King",
    description: "Lezzetli burgerler ve patates kızartması.",
    image: "https://picsum.photos/250/250",
    star: 4.0,
    distance: 1.5,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "6",
    name: "KFC",
    description: "Tavuk severler için en iyi seçenek.",
    image: "https://picsum.photos/200/200",
    star: 4.3,
    distance: 1.2,
    category: ["Burger", "Tavuk"],
    city: "Sakarya",
  },
  {
    id: "7",
    name: "Pizza Hut",
    description: "En iyi pizzalar burada!",
    image: "https://picsum.photos/2600/260",
    star: 4.5,
    distance: 2.8,
    category: ["Pizza"],
    city: "Ankara",
  },
  {
    id: "8",
    name: "Yıldız Pastanesi",
    description: "Taze ve lezzetli pastalar.",
    image: "https://picsum.photos/280/280",
    star: 4.4,
    distance: 2.2,
    category: ["Pastane", "Tatlı"],
    city: "Ankara",
  },
  {
    id: "9",
    name: "Simit Sarayı",
    description: "Taze simit ve çay keyfi.",
    image: "https://picsum.photos/290/290",
    star: 4.0,
    distance: 1.8,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Ankara",
  },
  {
    id: "10",
    name: "Cook Time",
    description: "En iyi hamburgerler burada!",
    image: "https://picsum.photos/300/300",
    star: 4.7,
    distance: 1.0,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "11",
    name: "Çaycı İsmail",
    description: "Geleneksel Türk çayı ve simit.",
    image: "https://picsum.photos/310/310",
    star: 4.2,
    distance: 0.8,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "İzmir",
  },
  {
    id: "12",
    name: "Mado",
    description: "Dondurma ve tatlı çeşitleri.",
    image: "https://picsum.photos/320/320",
    star: 4.9,
    distance: 1.5,
    category: ["İçecek", "Pastane", "Tatlı", "Dondurma"],
    city: "İstanbul",
  },
  {
    id: "13",
    name: "Saray Muhallebicisi",
    description: "Geleneksel Türk tatlıları.",
    image: "https://picsum.photos/330/330",
    star: 4.3,
    distance: 2.5,
    category: ["Pastane", "Tatlı"],
    city: "İstanbul",
  },
  {
    id: "14",
    name: "Çikolata Dünyası",
    description: "Çikolata severler için cennet.",
    image: "https://picsum.photos/340/340",
    star: 4.6,
    distance: 1.7,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
  {
    id: "15",
    name: "Dondurma Durağı",
    description: "Yazın vazgeçilmezi dondurmalar.",
    image: "https://picsum.photos/350/350",
    star: 4.8,
    distance: 2.0,
    category: ["İçecek", "Pastane", "Tatlı", "Dondurma"],
    city: "Sakarya",
  },
  {
    id: "16",
    name: "Çay Bahçesi",
    description: "Geleneksel Türk çayı ve atıştırmalıklar.",
    image: "https://picsum.photos/360/360",
    star: 4.1,
    distance: 1.3,
    category: ["İçecek", "Pastane", "Tatlı", "Dondurma"],
    city: "İstanbul",
  },
  {
    id: "17",
    name: "Kumpirci",
    description: "En iyi kumpir çeşitleri.",
    image: "https://picsum.photos/370/370",
    star: 4.4,
    distance: 1.9,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "İzmir",
  },
  {
    id: "18",
    name: "Çikolata Evi",
    description: "El yapımı çikolatalar.",
    image: "https://picsum.photos/380/380",
    star: 4.5,
    distance: 2.3,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
  {
    id: "19",
    name: "Popeyes",
    description: "Tavuk ve atıştırmalıklar.",
    image: "https://picsum.photos/390/390",
    star: 4.2,
    distance: 1.4,
    category: ["Burger", "Tavuk"],
    city: "Sakarya",
  },
  {
    id: "20",
    name: "Tavuk Dünyası",
    description: "Tavuk severler için en iyi seçenek.",
    image: "https://picsum.photos/400/400",
    star: 4.3,
    distance: 1.6,
    category: ["Burger", "Tavuk"],
    city: "Sakarya",
  },
  {
    id: "21",
    name: "Sushi House",
    description: "Lezzetli suşi çeşitleri.",
    image: "https://picsum.photos/410/410",
    star: 4.5,
    distance: 2.1,
    category: ["Uzak Doğu"],
    city: "Sakarya",
  },
  {
    id: "22",
    name: "SushiCo",
    description: "En iyi suşi çeşitleri.",
    image: "https://picsum.photos/420/420",
    star: 4.4,
    distance: 1.8,
    category: ["Uzak Doğu"],
    city: "Ankara",
  },
  {
    id: "23",
    name: "Little Caesar's",
    description: "Hızlı ve lezzetli pizzalar.",
    image: "https://picsum.photos/430/430",
    star: 4.1,
    distance: 1.9,
    category: ["Pizza"],
    city: "Sakarya",
  },
  {
    id: "24",
    name: "Edeler Dondurma",
    description: "En iyi dondurmalar burada!",
    image: "https://picsum.photos/440/440",
    star: 4.7,
    distance: 2.4,
    category: ["Dondurma"],
    city: "Sakarya",
  },
  {
    id: "25",
    name: "Çaycı Ali",
    description: "Geleneksel Türk çayı ve simit.",
    image: "https://picsum.photos/450/450",
    star: 4.2,
    distance: 1.1,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "İzmir",
  },
];

export const starCompanies = [
  {
    id: "1",
    name: "Pizza Hut",
    description: "En iyi pizzalar burada!",
    image: "https://picsum.photos/2600/260",
    star: 4.5,
    distance: 2.8,
    category: ["Pizza"],
    city: "Ankara",
  },
  {
    id: "2",
    name: "Burger King",
    description: "Lezzetli burgerler ve patates kızartması.",
    image: "https://picsum.photos/250/250",
    star: 4.0,
    distance: 1.5,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "3",
    name: "Domino's Pizza",
    description: "Hızlı teslimat ve taze malzemeler.",
    image: "https://picsum.photos/210/210",
    star: 4.2,
    distance: 3.0,
    category: ["Pizza"],
    city: "Ankara",
  },
  {
    id: "4",
    name: "Starbucks",
    description: "Kahve ve tatlı keyfi.",
    image: "https://picsum.photos/230/230",
    star: 4.8,
    distance: 0.5,
    category: ["İçecek", "Pastane"],
    city: "Ankara",
  },
  {
    id: "5",
    name: "McDonald's",
    description: "Hızlı ve lezzetli yemekler.",
    image: "https://picsum.photos/240/240",
    star: 4.1,
    distance: 2.0,
    category: ["Fast Food"],
    city: "Sakarya",
  },
  {
    id: "6",
    name: "KFC",
    description: "Tavuk severler için en iyi seçenek.",
    image: "https://picsum.photos/200/200",
    star: 4.3,
    distance: 1.2,
    category: ["Fast Food"],
    city: "Sakarya",
  },
  {
    id: "7",
    name: "Cook Time",
    description: "En iyi hamburgerler burada!",
    image: "https://picsum.photos/300/300",
    star: 4.7,
    distance: 1.0,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "8",
    name: "Kahve Dünyası",
    description: "Türk kahvesi ve tatlı çeşitleri.",
    image: "https://picsum.photos/220/220",
    star: 4.6,
    distance: 3.5,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
];
