export const allCompanies = [
  {
    id: "1",
    name: "Kahve Dünyası",
    description: "Türk kahvesi ve tatlı çeşitleri.",
    image: "https://picsum.photos/220/220",
    star: 4.6,
    distance: 3.5,
  },
  {
    id: "2",
    name: "McDonald's",
    description: "Hızlı ve lezzetli yemekler.",
    image: "https://picsum.photos/240/240",
    star: 4.1,
    distance: 2.0,
  },
  {
    id: "3",
    name: "Domino's Pizza",
    description: "Hızlı teslimat ve taze malzemeler.",
    image: "https://picsum.photos/210/210",
    star: 4.2,
    distance: 3.0,
  },
  {
    id: "4",
    name: "Starbucks",
    description: "Kahve ve tatlı keyfi.",
    image: "https://picsum.photos/230/230",
    star: 4.8,
    distance: 0.5,
  },
  {
    id: "5",
    name: "Burger King",
    description: "Lezzetli burgerler ve patates kızartması.",
    image: "https://picsum.photos/250/250",
    star: 4.0,
    distance: 1.5,
  },
  {
    id: "6",
    name: "KFC",
    description: "Tavuk severler için en iyi seçenek.",
    image: "https://picsum.photos/200/200",
    star: 4.3,
    distance: 1.2,
  },
  {
    id: "7",
    name: "Pizza Hut",
    description: "En iyi pizzalar burada!",
    image: "https://picsum.photos/2600/260",
    star: 4.5,
    distance: 2.8,
  },
  {
    id: "8",
    name: "Yıldız Pastanesi",
    description: "Taze ve lezzetli pastalar.",
    image: "https://picsum.photos/280/280",
    star: 4.4,
    distance: 2.2,
  },
  {
    id: "9",
    name: "Simit Sarayı",
    description: "Taze simit ve çay keyfi.",
    image: "https://picsum.photos/290/290",
    star: 4.0,
    distance: 1.8,
  },
  {
    id: "10",
    name: "Cook Time",
    description: "En iyi hamburgerler burada!",
    image: "https://picsum.photos/300/300",
    star: 4.7,
    distance: 1.0,
  },
];
