export const allCompanies = [
  {
    id: "1",
    name: "Kahve Dünyası",
    description: "Türk kahvesi ve tatlı çeşitleri.",
    image: "kahve-dunyasi",
    star: 4.6,
    distance: 3.5,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
  {
    id: "2",
    name: "McDonald's",
    description: "Hızlı ve lezzetli yemekler.",
    image: "mc-donalds",
    star: 4.1,
    distance: 2.0,
    category: ["Burger"],
    city: "Ankara",
  },
  {
    id: "3",
    name: "Domino's Pizza",
    description: "Hızlı teslimat ve taze malzemeler.",
    image: "dominos",
    star: 4.2,
    distance: 3.0,
    category: ["Pizza"],
    city: "Sakarya",
  },
  {
    id: "4",
    name: "Starbucks",
    description: "Kahve ve tatlı keyfi.",
    image: "starbucks",
    star: 4.8,
    distance: 0.5,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
  {
    id: "5",
    name: "Burger King",
    description: "Lezzetli burgerler ve patates kızartması.",
    image: "burger-king",
    star: 4.0,
    distance: 1.5,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "6",
    name: "KFC",
    description: "Tavuk severler için en iyi seçenek.",
    image: "kfc",
    star: 4.3,
    distance: 1.2,
    category: ["Burger", "Tavuk"],
    city: "Sakarya",
  },
  {
    id: "7",
    name: "Pizza Hut",
    description: "En iyi pizzalar burada!",
    image: "pizza-hut.jpg",
    star: 4.5,
    distance: 2.8,
    category: ["Pizza"],
    city: "Ankara",
  },
  {
    id: "8",
    name: "Yıldız Pastanesi",
    description: "Taze ve lezzetli pastalar.",
    image: "yildiz-pastanesi",
    star: 4.4,
    distance: 2.2,
    category: ["Pastane", "Tatlı"],
    city: "Ankara",
  },
  {
    id: "9",
    name: "Simit Sarayı",
    description: "Taze simit ve çay keyfi.",
    image: "simit-sarayı",
    star: 4.0,
    distance: 1.8,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Ankara",
  },
  {
    id: "10",
    name: "Cook Time",
    description: "En iyi hamburgerler burada!",
    image: "cook-time",
    star: 4.7,
    distance: 1.0,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "11",
    name: "Mado",
    description: "Dondurma ve tatlı çeşitleri.",
    image: "mado",
    star: 4.9,
    distance: 1.5,
    category: ["İçecek", "Pastane", "Tatlı", "Dondurma"],
    city: "İstanbul",
  },
  {
    id: "12",
    name: "Saray Muhallebicisi",
    description: "Geleneksel Türk tatlıları.",
    image: "pizza-hut.jpg",
    star: 4.3,
    distance: 2.5,
    category: ["Pastane", "Tatlı"],
    city: "İstanbul",
  },
  {
    id: "13",
    name: "Dondurma Durağı",
    description: "Yazın vazgeçilmezi dondurmalar.",
    image: "dondurma",
    star: 4.8,
    distance: 2.0,
    category: ["İçecek", "Pastane", "Tatlı", "Dondurma"],
    city: "Sakarya",
  },
  {
    id: "14",
    name: "Popeyes",
    description: "Tavuk ve atıştırmalıklar.",
    image: "popeyes",
    star: 4.2,
    distance: 1.4,
    category: ["Burger", "Tavuk"],
    city: "Sakarya",
  },
  {
    id: "15",
    name: "Tavuk Dünyası",
    description: "Tavuk severler için en iyi seçenek.",
    image: "tavuk-dunyasi",
    star: 4.3,
    distance: 1.6,
    category: ["Burger", "Tavuk"],
    city: "Sakarya",
  },
  {
    id: "16",
    name: "Sushi House",
    description: "Lezzetli suşi çeşitleri.",
    image: "sushi-house",
    star: 4.5,
    distance: 2.1,
    category: ["Uzak Doğu"],
    city: "Sakarya",
  },
  {
    id: "17",
    name: "SushiCo",
    description: "En iyi suşi çeşitleri.",
    image: "sushico",
    star: 4.4,
    distance: 1.8,
    category: ["Uzak Doğu"],
    city: "Ankara",
  },
  {
    id: "18",
    name: "Little Caesar's",
    description: "Hızlı ve lezzetli pizzalar.",
    image: "little-caesars",
    star: 4.1,
    distance: 1.9,
    category: ["Pizza"],
    city: "Sakarya",
  },
  {
    id: "19",
    name: "Edeler Dondurma",
    description: "En iyi dondurmalar burada!",
    image: "edeler",
    star: 4.7,
    distance: 2.4,
    category: ["Dondurma"],
    city: "Sakarya",
  },
];

export const starCompanies = [
  {
    id: "7",
    name: "Pizza Hut",
    description: "En iyi pizzalar burada!",
    image: "pizza-hut.jpg",
    star: 4.5,
    distance: 2.8,
    category: ["Pizza"],
    city: "Ankara",
  },
  {
    id: "5",
    name: "Burger King",
    description: "Lezzetli burgerler ve patates kızartması.",
    image: "burger-king",
    star: 4.0,
    distance: 1.5,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "3",
    name: "Domino's Pizza",
    description: "Hızlı teslimat ve taze malzemeler.",
    image: "dominos",
    star: 4.2,
    distance: 3.0,
    category: ["Pizza"],
    city: "Ankara",
  },
  {
    id: "4",
    name: "Starbucks",
    description: "Kahve ve tatlı keyfi.",
    image: "starbucks",
    star: 4.8,
    distance: 0.5,
    category: ["İçecek", "Pastane"],
    city: "Ankara",
  },
  {
    id: "2",
    name: "McDonald's",
    description: "Hızlı ve lezzetli yemekler.",
    image: "mc-donalds",
    star: 4.1,
    distance: 2.0,
    category: ["Fast Food"],
    city: "Sakarya",
  },
  {
    id: "6",
    name: "KFC",
    description: "Tavuk severler için en iyi seçenek.",
    image: "kfc",
    star: 4.3,
    distance: 1.2,
    category: ["Fast Food"],
    city: "Sakarya",
  },
  {
    id: "10",
    name: "Cook Time",
    description: "En iyi hamburgerler burada!",
    image: "cook-time",
    star: 4.7,
    distance: 1.0,
    category: ["Burger"],
    city: "Sakarya",
  },
  {
    id: "1",
    name: "Kahve Dünyası",
    description: "Türk kahvesi ve tatlı çeşitleri.",
    image: "kahve-dunyasi",
    star: 4.6,
    distance: 3.5,
    category: ["İçecek", "Pastane", "Tatlı"],
    city: "Sakarya",
  },
];
